version : '3.9'

services:
  server:
   container_name: ecommerce_backend
   image: ecommerce-backend:0.0.1
   build:
    context: .
   ports:
    - ${PORT}:${PORT}
   environment:
    DEV_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/ecommerce_db
    DB_USER: postgres
    DB_PASSWORD: postgres
    DB_NAME: ecommerce_db
    DB_HOST: node_psql_db
    DB_PORT: 5432
   networks:
    - shared-network
   volumes:
     - .:/app
     - /app/node_modules
   depends_on:
    - db
    
  db:
   container_name: postgres_db
   image: "postgres"
   ports:
     - "5433:5432"
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: ecommerce_db
   networks:
    - shared-network
   volumes :
     - nps_data:/var/lib/postgresql/data
volumes:
  nps_data:
networks: 
  shared-network:





 